name: Build and Deploy Docs

# Deploy docs only for master
on:
  push:
    branches:
      - "master"

# Allow deployment to GitHub Pages
permissions:
  pages: write
  id-token: write

jobs:
  deploy-docs:

    name: Deploy Docs

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y \
          docbook-xml \
          docbook-xsl \
          libxml2-utils \
          xsltproc \
          fop

    - name: Clone pgSphere
      uses: actions/checkout@v4

    - name: Build docs
      run: make -C doc

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'doc/html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
